import { describe, it, expect, beforeEach } from 'vitest'
import { render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from '../App'
beforeEach(()=> localStorage.clear())

describe('EntryFormModal', ()=>{
  it('empty name shows inline error and not save', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    const dialog = await screen.findByRole('dialog')
    await user.click(within(dialog).getByRole('button', {name:/^save$/i}))
    expect(await within(dialog).findByText(/restaurant name is required/i)).toBeInTheDocument()
  })
  it('empty city shows error', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    const dialog = await screen.findByRole('dialog')
    await user.type(within(dialog).getByLabelText(/restaurant name/i), 'A')
    await user.click(within(dialog).getByRole('button', {name:/^save$/i}))
    expect(await within(dialog).findByText(/city is required/i)).toBeInTheDocument()
  })
  it('Been There without rating blocks', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    const dialog = await screen.findByRole('dialog')
    await user.type(within(dialog).getByLabelText(/restaurant name/i), 'A')
    await user.type(within(dialog).getByLabelText(/^city/i), 'HK')
    await user.click(within(dialog).getByRole('button', {name:/been there/i}))
    await user.click(within(dialog).getByRole('button', {name:/^save$/i}))
    expect(await within(dialog).findByText(/pick a rating/i)).toBeInTheDocument()
  })
  it('Want to Try allows no rating', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    const dialog = await screen.findByRole('dialog')
    await user.type(within(dialog).getByLabelText(/restaurant name/i), 'WantSpot')
    await user.type(within(dialog).getByLabelText(/^city/i), 'HK')
    await user.click(within(dialog).getByRole('button', {name:/^save$/i}))
    expect(await screen.findByText('WantSpot')).toBeInTheDocument()
  })
  it('valid submission saves', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    const dialog = await screen.findByRole('dialog')
    await user.type(within(dialog).getByLabelText(/restaurant name/i), 'Valid')
    await user.type(within(dialog).getByLabelText(/^city/i), 'HK')
    await user.click(within(dialog).getByRole('button', {name:/^save$/i}))
    expect(await screen.findByText('Valid')).toBeInTheDocument()
  })
  it('cancel closes without save', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    const dialog = await screen.findByRole('dialog')
    await user.type(within(dialog).getByLabelText(/restaurant name/i), 'CancelTest')
    await user.click(within(dialog).getByRole('button', {name:/cancel/i}))
    expect(screen.queryByText('CancelTest')).not.toBeInTheDocument()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
  it('editing shows existing values', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    let dialog = await screen.findByRole('dialog')
    await user.type(within(dialog).getByLabelText(/restaurant name/i), 'EditMe')
    await user.type(within(dialog).getByLabelText(/^city/i), 'HK')
    await user.type(within(dialog).getByLabelText(/must-order dish/i), 'Siu mai')
    await user.click(within(dialog).getByRole('button', {name:/^save$/i}))
    await user.click(screen.getByRole('button', {name:/edit/i}))
    dialog = await screen.findByRole('dialog')
    expect(within(dialog).getByLabelText(/restaurant name/i)).toHaveValue('EditMe')
    expect(within(dialog).getByLabelText(/must-order dish/i)).toHaveValue('Siu mai')
  })
  it('flip Been There to Want removes rating requirement', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    let dialog = await screen.findByRole('dialog')
    await user.type(within(dialog).getByLabelText(/restaurant name/i), 'FlipReq')
    await user.type(within(dialog).getByLabelText(/^city/i), 'HK')
    await user.click(within(dialog).getByRole('button', {name:/been there/i}))
    await user.click(within(dialog).getByRole('radio', {name:/5 of 5 dumplings/}))
    await user.click(within(dialog).getByRole('button', {name:/^save$/i}))
    await user.click(screen.getByRole('button', {name:/edit/i}))
    dialog = await screen.findByRole('dialog')
    await user.click(within(dialog).getByRole('button', {name:/want to try/i}))
    await user.click(within(dialog).getByRole('button', {name:/^save$/i}))
    expect(await screen.findByText('FlipReq')).toBeInTheDocument()
  })
  it('note max length shows counter', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    const dialog = await screen.findByRole('dialog')
    expect(within(dialog).getByText(/0\/200/)).toBeInTheDocument()
    await user.type(within(dialog).getByLabelText(/^note/i), 'hello')
    expect(within(dialog).getByText(/5\/200/)).toBeInTheDocument()
  })
  it('Escape and close button both close', async ()=>{
    const user = userEvent.setup(); render(<App/>)
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    await user.click(screen.getByRole('button', {name:/add restaurant/i}))
    await user.click(screen.getByLabelText(/close/i))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
})
